200923

diff --git a/install b/install
--- a/install
+++ b/install
@@ -12,3 +12,113 @@
 #   This program is distributed in the hope that it will be useful, but WITHOUT
 # ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 # FOR A PARTICULAR PURPOSE.
+
+copy()
+{
+  sudo cp $1 $2
+  echo "  $1 -> $2"
+}
+
+# constans
+SWN1="MM8D"
+SWN2="mm8d"
+SWV=`cat documents/VERSION`
+INSTDIR="local"
+LANGUAGES="hu"
+SUBDIRS="/usr/$INSTDIR/bin \
+         /usr/$INSTDIR/etc \
+         /usr/$INSTDIR/etc/$SWN2 \
+         /usr/$INSTDIR/share \
+         /usr/$INSTDIR/share/doc \
+         /usr/$INSTDIR/share/doc/$SWN2 \
+         /usr/$INSTDIR/share/locale \
+         /usr/$INSTDIR/share/$SWN2 \
+         /usr/$INSTDIR/share/man \
+         /usr/$INSTDIR/share/man/man1 \
+         /var/$INSTDIR/lib/$SWN2 \
+         /var/$INSTDIR/lock \
+         /var/$INSTDIR/log \
+         /var/www/ \
+         /var/www/html \
+         /var/www/html/pics"
+README="/usr/$INSTDIR/share/doc/$SWN2/README"
+
+# installer
+clear
+echo "--------------------------------------------------------------------------------"
+echo "$SWN1 $SWV installer script"
+echo "Copyright (C) 2020 Pozsár Zsolt <pozsar.zsolt@szerafingomba.hu>"
+echo "--------------------------------------------------------------------------------"
+echo "  This program is free software: you can redistribute it and/or modify it
+under the terms of the European Union Public License 1.1 version.
+
+  This program is distributed in the hope that it will be useful, but WITHOUT
+ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
+FOR A PARTICULAR PURPOSE."
+echo "--------------------------------------------------------------------------------"
+sleep 3
+
+if ! [ -x "$(command -v apache2)" ]; then
+  echo 'ERROR: Run prepare script firstly!';
+  exit;
+fi
+
+echo -e "\nInstalling..."
+echo "- creating directories:"
+sudo mkdir --parents /usr/$INSTDIR 2> /dev/null
+for D in $SUBDIRS
+do
+  sudo mkdir --parents $D 2> /dev/null
+  echo "  $D"
+done
+for X in $LANGUAGES; do
+  if [ -e "messages/"$SWN2"_"$X".msg" ];
+  then
+    sudo mkdir --parents /usr/$INSTDIR/share/locale/$X 2> /dev/null
+    echo "  /usr/$INSTDIR/share/locale/$X"
+  fi;
+done
+sudo chown root:www-data /var/www/html/pics
+sudo chmod 775 /var/www/html/pics
+sudo chmod 777 /var/$INSTDIR/lib/$SWN2
+sudo chmod 2777 /usr/$INSTDIR/etc/$SWN2
+sudo chmod 664 /usr/$INSTDIR/etc/$SWN2/envir.ini
+echo "- copying files:"
+copy "LICENCE" "/usr/$INSTDIR/share/doc/$SWN2/COPYING"
+copy "documents/*" "/usr/$INSTDIR/share/doc/$SWN2/"
+copy "manuals/*" "/usr/$INSTDIR/share/man/man1/"
+for X in $LANGUAGES; do
+  if [ -e "messages/"$SWN2"_"$X".msg" ];
+  then
+    copy "messages/"$SWN2"_"$X".msg" "/usr/$INSTDIR/share/locale/$X/$SWN2.msg"
+  fi;
+done
+copy "binary/*.bin" "/usr/$INSTDIR/bin/"
+copy "programs/*.py" "/usr/$INSTDIR/bin/"
+copy "scripts/*" "/usr/$INSTDIR/bin/"
+copy "settings/cron.d/*" "/etc/cron.d/"
+copy "settings/$SWN2/*.ini" "/usr/$INSTDIR/etc/$SWN2/"
+copy "settings/init.d/*" "/etc/init.d/"
+copy "settings/systemd/system/$SWN2.service" "/etc/systemd/system/"
+copy "webpage/cgi-bin/*.cgi" "/usr/lib/cgi-bin/"
+copy "webpage/*.css" "/var/www/html/"
+copy "webpage/*.html" "/usr/$INSTDIR/share/$SWN2/"
+copy "webpage/pics/*" "/var/www/html/pics/"
+sudo cat /etc/motd | grep -qv $SWN1 && sudo mv /etc/motd /etc/motd.orig && sudo cp settings/motd /etc/
+echo "- set init.d:"
+sudo /etc/init.d/$SWN2.sh stop
+sudo ln -sf /etc/init.d/$SWN2.sh /etc/rc0.d/K01$SWN2.sh
+sudo ln -sf /etc/init.d/$SWN2.sh /etc/rc2.d/S01$SWN2.sh
+sudo ln -sf /etc/init.d/$SWN2.sh /etc/rc3.d/S01$SWN2.sh
+sudo ln -sf /etc/init.d/$SWN2.sh /etc/rc4.d/S01$SWN2.sh
+sudo ln -sf /etc/init.d/$SWN2.sh /etc/rc5.d/S01$SWN2.sh
+sudo ln -sf /etc/init.d/$SWN2.sh /etc/rc6.d/K01$SWN2.sh
+sudo systemctl daemon-reload
+sudo systemctl enable $SWN2.service
+sudo /etc/init.d/$SWN2.sh start
+echo "- set cron.d:"
+copy settings/cron.d/$SWN2 /etc/cron.d/
+sudo /etc/init.d/cron restart
+echo "- create default startpage:"
+/usr/$INSTDIR/bin/$SWN2-updatestartpage
+echo "Done."
