220303

diff --git a/install b/install
--- a/install
+++ b/install
@@ -79,10 +79,10 @@ ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 FOR A PARTICULAR PURPOSE.\n"
 sleep 3
 
-if ! [ -x "$(command -v apache2)" ]; then
-  echo 'ERROR: Run prepare script firstly!';
-  exit;
-fi
+#if ! [ -x "$(command -v apache2)" ]; then
+#  echo 'ERROR: Run prepare script firstly!';
+#  exit;
+#fi
 echo -e "\nChecking binaries:"
 if [ $ARCH = 'x86_64' ]
 then
