200926

diff --git a/scripts/mm8d-creatediagrams b/scripts/mm8d-creatediagrams
--- a/scripts/mm8d-creatediagrams
+++ b/scripts/mm8d-creatediagrams
@@ -1,6 +1,6 @@
 #!/bin/bash
 # +----------------------------------------------------------------------------+
-# | MM8D v0.1 * Growing house controlling and remote monitoring system         |
+# | MM8D v0.1 * Growing house controlling and remote monitoring device         |
 # | Copyright (C) 2020 Pozsár Zsolt <pozsar.zsolt@szerafingomba.hu>            |
 # | mm8d-creatediagrams                                                        |
 # | Create diagrams for webpage                                                |
@@ -15,15 +15,15 @@
 
 # Exit codes:
 #   0: normal exit
-#   1: specified value is not number
-#   2: wrong channel number
-#   3: cannot open configuration file
+#   1: cannot open configuration file
+#   2: specified value is not number
+#   3: wrong channel number
 
 checkparameter()
 {
   if [[ ! $1 =~ ^[0-9]+$ ]]; then 
-    echo "ERROR #1: Specified value is not number!"
-    exit 1
+    echo "ERROR #2: Specified value is not number!"
+    exit 2
   fi
   if [ $1 -ge "1" ]
   then
@@ -35,11 +35,11 @@ checkparameter()
       else
         CHANNEL=$1
       fi
-    else
-      echo "ERROR #2: Wrong channel number!"
-      echo "Valid values: 1..16"
-      exit 2
     fi
+  else
+    echo "ERROR #3: Wrong channel number!"
+    echo "Valid values: 1..16"
+    exit 3
   fi
 }
 
@@ -49,8 +49,8 @@ loadconfiguration()
   CFGFILE="/usr/local/etc/mm8d/mm8d.ini"
   if [ ! -f $CFGFILE ]
   then
-    echo "ERROR #3: Cannot open $CFGFILE configuration file!"
-    exit 3
+    echo "ERROR #1: Cannot open $CFGFILE configuration file!"
+    exit 1
   fi
   DIR_HTM=`cat $CFGFILE | grep dir_htm= | sed 's/dir_htm=//'`
   DIR_LOG=`cat $CFGFILE | grep dir_log= | sed 's/dir_log=//'`
@@ -138,6 +138,16 @@ EOF
   rm --force $TMPFILE
 }
 
+usage()
+{
+  echo -e "\nUsage: $0 channel\n"
+  exit 0
+}
+
+if [ $# -eq 0 ]
+then
+  usage
+fi
 checkparameter $1
 loadconfiguration
 creatediagrams
diff --git a/scripts/mm8d-editenvirconf b/scripts/mm8d-editenvirconf
--- a/scripts/mm8d-editenvirconf
+++ b/scripts/mm8d-editenvirconf
@@ -15,14 +15,14 @@
 
 # Exit codes:
 #   0: normal exit
-#   1: specified value is not number
-#   2: wrong channel number
-#   3: cannot open configuration file
+#   1: cannot open configuration file
+#   2: specified value is not number
+#   3: wrong channel number
 
 read -p "Channel (1-16): " CHANNEL
 if [[ ! "$CHANNEL" =~ ^[0-9]+$ ]]; then 
-  echo "ERROR #1: Specified value is not number!"
-  exit 1
+  echo "ERROR #2: Specified value is not number!"
+  exit 2
 fi
 if [ $CHANNEL -ge "1" ]
 then
@@ -37,8 +37,8 @@ then
     fi
     if [ ! -f $CFGFILE ]
     then
-      echo "ERROR #3: Cannot open $CFGFILE configuration file!"
-      exit 3
+      echo "ERROR #1: Cannot open $CFGFILE configuration file!"
+      exit 1
     fi
     sudo mm8d-editenvirconf.bin $CFGFILE
     if [ $? -eq 0 ]
@@ -47,9 +47,13 @@ then
       mm8d-startdaemon
     fi
   else
-    echo "ERROR #2: Wrong channel number!"
+    echo "ERROR #3: Wrong channel number!"
     echo "Valid values: 1..16"
-    exit 2
+    exit 3
   fi
+else
+  echo "ERROR #3: Wrong channel number!"
+  echo "Valid values: 1..16"
+  exit 3
 fi
 exit 0
diff --git a/scripts/mm8d-getsnapshots b/scripts/mm8d-getsnapshots
--- a/scripts/mm8d-getsnapshots
+++ b/scripts/mm8d-getsnapshots
@@ -1,6 +1,6 @@
 #!/bin/bash
 # +----------------------------------------------------------------------------+
-# | MM8D v0.1 * Growing house controlling and remote monitoring system         |
+# | MM8D v0.1 * Growing house controlling and remote monitoring device         |
 # | Copyright (C) 2020 Pozsár Zsolt <pozsar.zsolt@szerafingomba.hu>            |
 # | mm8d-getsnapshots                                                          |
 # | Get snapshot from IP cameras                                               |
@@ -15,15 +15,15 @@
 
 # Exit codes:
 #   0: normal exit
-#   1: specified value is not number
-#   2: wrong channel number
-#   3: cannot open configuration file
+#   1: cannot open configuration file
+#   2: specified value is not number
+#   3: wrong channel number
 
 checkparameter()
 {
   if [[ ! $1 =~ ^[0-9]+$ ]]; then 
-    echo "ERROR #1: Specified value is not number!"
-    exit 1
+    echo "ERROR #2: Specified value is not number!"
+    exit 2
   fi
   if [ $1 -ge "1" ]
   then
@@ -35,11 +35,11 @@ checkparameter()
       else
         CHANNEL=$1
       fi
-    else
-      echo "ERROR #2: Wrong channel number!"
-      echo "Valid values: 1..16"
-      exit 2
     fi
+  else
+    echo "ERROR #3: Wrong channel number!"
+    echo "Valid values: 1..16"
+    exit 3
   fi
 }
 
@@ -49,8 +49,8 @@ loadconfiguration()
   CFGFILE="/usr/local/etc/mm8d/mm8d.ini"
   if [ ! -f $CFGFILE ]
   then
-    echo "ERROR #3: Cannot open $CFGFILE configuration file!"
-    exit 3
+    echo "ERROR #1: Cannot open $CFGFILE configuration file!"
+    exit 1
   fi
   CAM_CH01=`cat $CFGFILE | grep cam_ch01= | sed 's/cam_ch01=//'`
   CAM_CH02=`cat $CFGFILE | grep cam_ch02= | sed 's/cam_ch02=//'`
@@ -89,6 +89,16 @@ getsnapshots()
   fi
 }
 
+usage()
+{
+  echo -e "\nUsage: $0 channel\n"
+  exit 0
+}
+
+if [ $# -eq 0 ]
+then
+  usage
+fi
 checkparameter $1
 loadconfiguration
 getsnapshots
diff --git a/scripts/mm8d-viewlog b/scripts/mm8d-viewlog
--- a/scripts/mm8d-viewlog
+++ b/scripts/mm8d-viewlog
@@ -1,6 +1,6 @@
 #!/bin/bash
 # +----------------------------------------------------------------------------+
-# | MM8D v0.1 * Growing house controlling and remote monitoring system         |
+# | MM8D v0.1 * Growing house controlling and remote monitoring device         |
 # | Copyright (C) 2020 Pozsár Zsolt <pozsar.zsolt@szerafingomba.hu>            |
 # | mm8d-viewlog                                                               |
 # | View log file                                                              |
@@ -15,10 +15,10 @@
 
 # Exit codes:
 #   0: normal exit
-#   1: specified value is not number
-#   2: wrong channel number
-#   3: cannot open configuration file
-#   4: cannot open log file
+#   1: cannot open configuration file
+#   2: specified value is not number
+#   3: wrong channel number
+#   5: cannot open log file
 
 loadconfiguration()
 {
@@ -26,8 +26,8 @@ loadconfiguration()
   CFGFILE="/usr/local/etc/mm8d/mm8d.ini"
   if [ ! -f $CFGFILE ]
     then
-      echo "ERROR #3: Cannot open configuration file!"
-      exit 3
+      echo "ERROR #1: Cannot open configuration file!"
+      exit 1
   fi
   DIR_LOG=`cat $CFGFILE | grep dir_log= | sed 's/dir_log=//'`
 }
@@ -72,8 +72,8 @@ viewlogfile()
 # main function
 read -p "Channel (0-16): " CHANNEL
 if [[ ! "$CHANNEL" =~ ^[0-9]+$ ]]; then 
-  echo "ERROR #1: Specified value is not number!"
-  exit 1
+  echo "ERROR #2: Specified value is not number!"
+  exit 2
 fi
 loadconfiguration
 if [ $CHANNEL -ge "0" ]
@@ -89,14 +89,14 @@ then
     fi
     if [ ! -f $LOGFILE ]
     then
-      echo "ERROR #4: Cannot open $LOGFILE log file!"
-      exit 4
+      echo "ERROR #5: Cannot open $LOGFILE log file!"
+      exit 5
     fi
     viewlogfile
   else
-    echo "ERROR #2: Wrong channel number!"
-    echo "Valid values: 1..16"
-    exit 2
+    echo "ERROR #3: Wrong channel number!"
+    echo "Valid values: 0..16"
+    exit 3
   fi
 fi
 exit 0
