230512

diff --git a/scripts/mm8d-creatediagrams b/scripts/mm8d-creatediagrams
--- a/scripts/mm8d-creatediagrams
+++ b/scripts/mm8d-creatediagrams
@@ -29,10 +29,10 @@ fi
 
 checkparameter()
 {
-#  if [[ ! $1 =~ ^[0-9]+$ ]]; then 
-#    echo "ERROR #2: Specified value is not number!"
-#    exit 2
-#  fi
+  if [[ ! $1 =~ ^-?[0-9]+$ ]]; then 
+    echo "ERROR #2: Specified value is not number!"
+    exit 2
+  fi
   if [ $1 -ge "-1" ]
   then
     if [ $1 -le "8" ]
